// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WorldRank.Infrastructure.Persistence.Context;

#nullable disable

namespace WorldRank.Infrastructure.Migrations
{
    [DbContext(typeof(WorldRankDBContext))]
    [Migration("20260712140000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("WorldRank.Domain.Entities.Player", b =>
            {
                b.Property<int>("Id")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnType("varchar(100)");

                b.Property<int>("Score")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Players");
            });

            modelBuilder.Entity("WorldRank.Domain.Entities.Wallet", b =>
            {
                b.Property<int>("Id")
                    .HasColumnType("int");

                b.Property<decimal>("Balance")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasColumnType("varchar(3)");

                b.Property<bool>("IsBlocked")
                    .HasColumnType("bit");

                b.Property<int>("PlayerId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex(new[] { "PlayerId", "Currency" }, "IX_Wallets_PlayerId_Currency")
                    .IsUnique();

                b.ToTable("Wallets");
            });

            modelBuilder.Entity("WorldRank.Domain.Entities.Wallet", b =>
            {
                b.HasOne("WorldRank.Domain.Entities.Player", null)
                    .WithMany()
                    .HasForeignKey("PlayerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_Wallets_Players");
            });
        }
    }
}
